version: "3.3"
services:
  xmpp:
    image: ejabberd/ecs
    platform: "linux/amd64"
    environment:
      - CTL_ON_CREATE=register admin localhost asd
      - CTL_ON_START=registered_users localhost ;
                     status
    network_mode: host
  server_ws:
    build: .
    command: python server_ws/run.py
    ports:
      - 9007:9007
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1

  web_client:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./web_client:/usr/share/nginx/html

  agent_1:
    build: .
    command: python agent_1/run.py
    environment:
      - PYTHONUNBUFFERED=1
      - XMPP_SERVER_URL=localhost
      - XMPP_SERVER_HOST=admin
      - XMPP_SERVER_PASSWORD=asd
      - WS_URL=127.0.0.1
      - WS_PORT=9007
    network_mode: host
    depends_on:
      - xmpp
