version: "3.3"
services:
  xmpp:
    image: ejabberd/ecs
    platform: "linux/amd64"
    environment:
      - CTL_ON_CREATE=register admin localhost asd
      - CTL_ON_START=registered_users localhost ;
                     status
    network_mode: host

  agent_1:
    build: .
    command: python agent_1/run.py
    environment:
      - PYTHONUNBUFFERED=1
      - XMPP_SERVER_URL=localhost
      - XMPP_SERVER_HOST=admin
      - XMPP_SERVER_PASSWORD=asd
    network_mode: host
    depends_on:
      - xmpp
