version: "3.3"
services:
  xmpp:
    image: ejabberd/ecs
    ports:
      - "5222:5222"
    environment:
     - CTL_ON_CREATE=register admin localhost passw0rd
    networks:
      - agents_net
  agent_1:
    build: .
    command: python agent_test/run.py
      - xmpp-server
    networks:
      - agents_net
    depends_on:
      - xmpp

networks:
  agents_net:
  
  # agent_2:
  #  build: .
  #  command: python agent_test_2/run.py
