version: "3.3"
services:
  xmpp:
    image: ejabberd/ecs
    platform: "linux/amd64"
    environment:
      - CTL_ON_CREATE=register admin localhost asd ; 
        register g1 localhost asd ; 
        register g2 localhost asd ; 
        register c1 localhost asd ; 
        register c2 localhost asd ; 
        register c3 localhost asd ;

      - CTL_ON_START=registered_users localhost ;
                     status
    network_mode: host
  server_ws:
    build: .
    command: python server_ws/run.py
    ports:
      - 9007:9007
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1

  web_client:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./web_client:/usr/share/nginx/html

  agent_1:
    build: .
    command: python agents/run.py
    environment:
      - PYTHONUNBUFFERED=1
      - XMPP_SERVER_URL=localhost
      - XMPP_SERVER_HOST=admin
      - XMPP_SERVER_PASSWORD=asd
      - WS_URL=127.0.0.1
      - WS_PORT=9007
      - AGENT_CLEANER_NUMBER=3
      - AGENT_GUARD_NUMBER=2
      - AGENT_GUIDE_NUMBER=0
    network_mode: host
    depends_on:
      - xmpp
